version: '3'

services:
  mydevjourney-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    volumes:
      - .:/gympass-api
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=mydevjourney
